### ISSUE TITLE
Sobre esus-aps

### ISSUE THREAD

**Issue by cyrosouzahernandez** [gunterbr/e_SUS_PEC-with-SSL#1]
Boa tarde,
Sou Cyro da Prefeitura de Itapema Santa Catarina. ao implemantar o certficado SSL no e-SUS APS [LINUX] ,  está ocorrendo erro:
 lengthTag=109, too big

Veja abaixo:
root@esus:/opt/e-SUS/webserver/config# keytool -importkeystore -srckeystore /opt/e-SUS/webserver/config/esusaps.jks -destkeystore /opt/e-SUS/webserver/config/esusaps.p12 -srcstoretype JKS -deststoretype PKCS12 -deststorepass 1t4p3ms@@ -srcstorepass 1t4p3ms@@
Importing keystore /opt/e-SUS/webserver/config/esusaps.jks to /opt/e-SUS/webserver/config/esusaps.p12...
keytool error: java.io.IOException: DerInputStream.getLength(): lengthTag=109, too big.

Agradeço desde já.

**Comment by gunterbr** [comment]
> Boa tarde, Sou Cyro da Prefeitura de Itapema Santa Catarina. ao implemantar o certficado SSL no e-SUS APS [LINUX] , está ocorrendo erro: lengthTag=109, too big
> 
> Veja abaixo: root@esus:/opt/e-SUS/webserver/config# keytool -importkeystore -srckeystore /opt/e-SUS/webserver/config/esusaps.jks -destkeystore /opt/e-SUS/webserver/config/esusaps.p12 -srcstoretype JKS -deststoretype PKCS12 -deststorepass 1t4p3ms@@ -srcstorepass 1t4p3ms@@ Importing keystore /opt/e-SUS/webserver/config/esusaps.jks to /opt/e-SUS/webserver/config/esusaps.p12... keytool error: java.io.IOException: DerInputStream.getLength(): lengthTag=109, too big.
> 
> Agradeço desde já.

Olá Cyro. Será que você poderia configurar o bash de renovação do certificado e executa-lo antes que possamos iniciar uma investigação sobre isso. Uma vez que você já baixou o certificado com certbot e executou o openssl

**Comment by cyrosouzahernandez** [comment]
Muito obrigado pelo retorno, vaos fazer e depois aviso.

**Comment by gunterbr** [comment]
> Muito obrigado pelo retorno, vaos fazer e depois aviso.

Olá Cyro, esperamos contar com seu feedback em breve para encerramos o tópico.

**Comment by cyrosouzahernandez** [comment]
Boa tarde, eu removi todo certificado e reinstalei novamente usando o seu tutorial deu certo. Muito obrigado pela atenção.

**Comment by cyrosouzahernandez** [comment]
Boa tarde, eu removi todo certificado e reinstalei novamente usando o seu tutorial deu certo. Muito obrigado pela atenção.
